# fly.toml app configuration file generated for space-agent on 2026-05-03T19:46:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'space-agent'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  CUSTOMWARE_PATH = '/data/customware'
  HOST = '0.0.0.0'

[[mounts]]
  source = 'customware'
  destination = '/data/customware'
  initial_size = '10gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '1m0s'
    method = 'GET'
    path = '/'

[[restart]]
  policy = 'on-failure'
  retries = 10

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
