[build]
builder = "docker"

[deploy]
startCommand = ["/docker-entrypoint.sh"]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

requiredMountPath= "/data/customware"

[variables]
CUSTOMWARE_PATH="/data/customware"

